sudo: false
language: rust
rust:
  - nightly
services:
  - docker

jobs:
  include:
    - stage: clippy backend
      before_script: cd backend/
      script:
        - rustup component add clippy
        - cargo +nightly clippy
    - stage: fmt backend
      before_script: cd backend/
      script:
        - rustup component add rustfmt
        - cargo +nightly fmt
    - stage: clippy frontend
      before_script: cd frontend/
      script:
        - rustup component add clippy
        - cargo +nightly clippy
    - stage: fmt frontend
      before_script: cd frontend/
      script:
        - rustup component add rustfmt
        - cargo +nightly fmt
    - stage: backend
      before_script: cd backend/ 
      script: cargo +nightly build
    - stage: frontend
      script: docker-compose build 

stages:
  - clippy backend
  - fmt backend
  - clippy frontend
  - fmt frontend
  - backend
  - frontend

