version: '3'

services:
  backend:
    image: rustlang/rust:nightly
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - ./backend:/usr/src/app
    command: bash -c "cd /usr/src/app && cargo install diesel_cli --no-default-features --features "sqlite" && diesel migration run && cargo +nightly run"
  frontend:
    build: frontend
    ports:
      - "0.0.0.0:8080:8080"

